/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-01-27 02:56:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Collection;
import java.util.ArrayList;
import java.util.HashMap;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");

	ArrayList<String> colorlist=new ArrayList();
	ArrayList<String> ViewUrl=new ArrayList(); 
	colorlist.add("#C71585");
	colorlist.add("#556b2f");
	colorlist.add("#191970");
	colorlist.add("#dc143c");
	colorlist.add("#9932cc");
	
	request.setCharacterEncoding("utf-8");
	String color = (String)request.getAttribute("postColor");
	String lab = (String)request.getAttribute("lab");
	System.out.println(lab);
	HashMap<String,HashMap<String,String>> WebPage=(HashMap)session.getAttribute("WebPage");
	HashMap<String,ArrayList> ClustResult = (HashMap)session.getAttribute("ClustResult");
	HashMap<String,ArrayList> DocLabels = (HashMap)session.getAttribute("DocLabels");

      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function right(){\n");
      out.write("\tif(");
      out.print(color);
      out.write("==null){\n");
      out.write("\t\tparent.right.location.href=\"./right.jsp\";\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("</head>\n");
      out.write("<body onload=\"right();\">\n");
      out.write("<font size=\"2px\">\n");
      out.write("<table>\n");

for (String url:WebPage.keySet()){
	for (String title:WebPage.get(url).keySet()){

      out.write("\n");
      out.write("\t\t<tr><td>\n");
      out.write("\t\t<a href=");
      out.print(url);
      out.write(" target=_blank>");
      out.print(title);
      out.write("</a><br>\n");
      out.write("\t\t");
      out.print(WebPage.get(url).get(title));
      out.write("\n");
      out.write("\t\t</td></tr>\n");
		
	}
}

      out.write("\n");
      out.write("</table>\n");
      out.write("</font>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
