/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-12-20 04:43:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.HashMap;

public final class right_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/jquery-1.5.2.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/jquery.history.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/raphael.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/vis4.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/Tween.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/build/bubbletree.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./BubbleTree/build/bubbletree.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/styles/cofog.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./right.css\" />\n");
      out.write("</head>\n");
      out.write("\n");

	HashMap<String,HashMap<String,String>>WebPage=(HashMap)session.getAttribute("WebPage");
	HashMap<String,ArrayList<String>>ClustResult=(HashMap)session.getAttribute("ClustResult");
	String keyword = (String)session.getAttribute("keyword");
	ArrayList<String> color=new ArrayList();
	color.add("#C71585");
	color.add("#556b2f");
	color.add("#191970");
	color.add("#dc143c");
	color.add("#9932cc");

      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function(){\n");
      out.write("\tvar data = {\n");
      out.write("\t\t\tlabel: '");
      out.print(keyword);
      out.write("',\n");
      out.write("\t\t\tamount: '");
      out.print(WebPage.size());
      out.write("',\n");
      out.write("\t\t\tchildren:[\n");

int i=0;
	for(String Label:ClustResult.keySet()){

      out.write("\n");
      out.write("\t\t\t\t{ label:'");
      out.print(Label);
      out.write("',amount:");
      out.print(ClustResult.get(Label).size());
      out.write(",color:'");
      out.print(color.get(i));
      out.write("',\n");
      out.write("\t\t\t\t\tchildren:[\n");
		
		for(int x=0;x<ClustResult.get(Label).size();x++){
			if(x+1!=ClustResult.get(Label).size()){

      out.write("\n");
      out.write("\t\t\t\t\t\t{label:'####',amount:1,color:'");
      out.print(color.get(i));
      out.write("'},\n");

			}else{

      out.write("\n");
      out.write("\t\t\t\t\t\t{label:'####',amount:1,color:'");
      out.print(color.get(i));
      out.write("'}]\t\n");

			}
		}
		if(i+1!=ClustResult.size()){

      out.write("\n");
      out.write("\t\t},\n");

		}else{

      out.write("\n");
      out.write("\t\t}\n");

		}
		i++;
	}

      out.write("\n");
      out.write("\t]};\n");
      out.write("\tnew BubbleTree({\n");
      out.write("\t\tdata:data,\n");
      out.write("\t\tbubbleType:'icon',\n");
      out.write("\t\tcontainer: '.bubbletree'\n");
      out.write("\t\t});\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("<form name=filter action=\"Filter\" target=\"left\" method=\"post\">\n");
      out.write("<input id=co name=col type=\"hidden\" value=#999999>\n");
      out.write("</form>\n");
      out.write("\t<div class=\"bubbletree\"></div>\n");
      out.write("\t<div id=\"foot\">\n");
      out.write("\t\tBuilt with <a href=\"http://okfnlabs.org/\">Bubble Tree</a> from the \n");
      out.write("\t\t<a href=\"http://okfn.org/\">Open Knowledge Foundation</a>. <br>Design\n");
      out.write("\t\tand implementation by <a href=\"http://driven-by-data.net/\">Gregor\n");
      out.write("\t\tAisch</a> and\n");
      out.write("\t\t<a href=\"http://www.informationisbeautiful.net/\">David McCandless</a>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
