/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-01-27 02:56:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import servlet.Start;
import java.util.ArrayList;
import java.util.HashMap;

public final class right_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/jquery-1.5.2.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/jquery.history.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/raphael.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/vis4.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/Tween.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/build/bubbletree.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./BubbleTree/build/bubbletree.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/styles/cofog.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./right.css\" />\n");
      out.write("</head>\n");
      out.write("\n");

        HashMap<String,HashMap<String,String>>WebPage=(HashMap)session.getAttribute("WebPage");
        HashMap<String,ArrayList<String>>ClustResult=(HashMap)session.getAttribute("ClustResult");
        HashMap<String,String>DocLabel = (HashMap)session.getAttribute("DocLabel");
        String keyword = (String)session.getAttribute("keyword");

      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function(){\n");
      out.write("        var data = {\n");
      out.write("                        label: '");
      out.print(keyword);
      out.write("',\n");
      out.write("                        amount: '");
      out.print(WebPage.size());
      out.write("',\n");
      out.write("                        children:[\n");

int i=0;
        for(String Label:ClustResult.keySet()){
        	System.out.println(Label);
        	System.out.println(ClustResult.get(Label).size());
        	System.out.println(Start.color.get(i));

      out.write("\n");
      out.write("                                { label:'");
      out.print(Label);
      out.write("<br>");
      out.print(ClustResult.get(Label).size());
      out.write("件',amount:");
      out.print(ClustResult.get(Label).size());
      out.write(",color:'");
      out.print(Start.color.get(i));
      out.write("',\n");
      out.write("                                        children:[\n");
                
                for(int x=0;x<ClustResult.get(Label).size();x++){
                		String url=ClustResult.get(Label).get(x);
                        if(x+1!=ClustResult.get(Label).size()){

      out.write("\t\n");
      out.write("                                                {label:'");
      out.print(DocLabel.get(url));
      out.write("',amount:1,color:'");
      out.print(Start.color.get(i));
      out.write("'},\n");

                        }else{

      out.write("\n");
      out.write("                                                {label:'");
      out.print(DocLabel.get(url));
      out.write("',amount:1,color:'");
      out.print(Start.color.get(i));
      out.write("'}]        \n");

                        }
                	
                }
                if(i+1!=ClustResult.size()){

      out.write("\n");
      out.write("                },\n");

                }else{

      out.write("\n");
      out.write("                }\n");

                }
                i++;
        }

      out.write("\n");
      out.write("        ]};\n");
      out.write("        new BubbleTree({\n");
      out.write("                data:data,\n");
      out.write("                bubbleType:'icon',\n");
      out.write("                container: '.bubbletree'\n");
      out.write("                });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("<form name=filter action=\"Filter\" target=\"left\" method=\"post\">\n");
      out.write("<input id=co name=col type=\"hidden\" value=#999999>\n");
      out.write("<input id=label name=lab type=\"hidden\" value=\"null\">\n");
      out.write("</form>\n");
      out.write("        <div class=\"bubbletree\"></div>\n");
      out.write("        <div id=\"foot\">\n");
      out.write("                Built with <a href=\"http://okfnlabs.org/\">Bubble Tree</a> from the \n");
      out.write("                <a href=\"http://okfn.org/\">Open Knowledge Foundation</a>. <br>Design\n");
      out.write("                and implementation by <a href=\"http://driven-by-data.net/\">Gregor\n");
      out.write("                Aisch</a> and\n");
      out.write("                <a href=\"http://www.informationisbeautiful.net/\">David McCandless</a>\n");
      out.write("        </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
